### ISSUE TITLE
Fix the build.xml file

### ISSUE THREAD

**Issue by cfhaak** [fun-with-editions/staribacher-static#10]
The current workflow for building the page fails, due to some none-existent index files which dse-cc expects per default:
https://github.com/fun-with-editions/staribacher-static/actions/runs/8299133453/job/22714137365#step:5:3179

Our site only contains a person index. Please find the build.xml file in the repo and remove the lines causing the trouble. (The build.xml file is a file describing the steps necessary to build the page)

**Comment by cfhaak** [comment]
related to https://github.com/fun-with-editions/staribacher-static/issues/11

**Comment by fsanzl** [comment]
Fixed
