### ISSUE TITLE
denormalizing entities

### ISSUE THREAD

**Issue by csae8092** [fun-with-editions/staribacher-static#127]
on build something like 
```
add-attributes -g "./data/editions/*.xml" -b "https://staribacher.acdh.oeaw.ac.at"
add-attributes -g "./data/meta/*.xml" -b "https://staribacher.acdh.oeaw.ac.at"
add-attributes -g "./data/indices/*.xml" -b "https://staribacher.acdh.oeaw.ac.at"
denormalize-indices -f "./data/editions/*.xml" -i "./data/indices/*.xml" -m ".//*[@ref]/@ref | .//*/@source" -x ".//tei:titleStmt/tei:title[@type='main']/text()"
``` 

should run, I'd put it into the fetch-data script; this will write documents where an entity was mentioned into the index file as well as the information about an entity into the document; but this will override existing tei:back elements, therefore https://github.com/fun-with-editions/staribacher-data/issues/13 needs to be fixed first

**Comment by fsanzl** [comment]
added xml:base to staribacher-data/data/editions/*.xml

**Comment by fsanzl** [comment]
Solved in https://github.com/fun-with-editions/staribacher-static/tree/128-mentions
