### ISSUE TITLE
setup typesense

### ISSUE THREAD

**Issue by cfhaak** [fun-with-editions/staribacher-static#3]
As soon as #7 is done you could basically start creating the search index. But maybe provide some help with other tasks first …
You could e.g. split the development of the search page between front (instant search) and backend (typesense index building)…

**Comment by cfhaak** [comment]
Anyway have a look at the [roadmap](#1) first …

**Comment by fsanzl** [comment]
- [ ] Search index 
- [ ] Volltext und Datum
- [ ] nach Person fazetieren

**Comment by cfhaak** [comment]
for creating the fulltext use peters pyutil function
https://github.com/acdh-oeaw/acdh-tei-pyutils/blob/517c0c8f7f6cd934fe7ec873da660ec9c763b47b/acdh_tei_pyutils/utils.py#L26

**Comment by fsanzl** [comment]
We need a xml:id for each document. 
Addressed in https://github.com/fun-with-editions/staribacher-data/issues/5

**Comment by cfhaak** [comment]
Nice! The search looks good so far!

**Comment by fsanzl** [comment]
- [ ] Index persons
   - [ ]  use ref -> xml:id  -> unique full name
   - [ ] Fazettierung
- [ ] Day/month/year
- [ ] 'Date' instead of 'Title'

**Comment by fsanzl** [comment]
According to TS manuals, it is advisable to represent dates as Unix timestamps, so they can be directly tested with numeric operators <, >, =, !=. Some source files contain texts covering a range of dates while others have a single day. I have added two additional int32 objects to the TS schema to represent the `date` attributes `@from` and `@to`, which become the same value if  the document provides just a `@when`.

**Comment by cfhaak** [comment]
Cool! That should work!

**Comment by fsanzl** [comment]
```python
{
    'project': 'STB',
    'id': 'staribacher__19760224',
    'resolver': '/staribacher__19760224.html',
    'rec_id': 'staribacher__19760224.xml',
    'title': 'Dienstag, der 24. Februar 1976',
    'year': '1976-02-24',
    'notbefore': 193964400,
    'notafter': 193964400,
    'persons': [
        'Androsch, Hannes',
        'Benya, Anton',
        'Dallinger, Alfred',
        'Horwath, Eugen',
        'Häuser, Rudolf',
        'Kienzl, Heinz',
        'Kreisky, Bruno',
        'Millendorfer, Franz',
        'Mock, Alois',
        'Sekanina, Karl',
        'Taus, Josef'],
    'anchor_link': 'Band29_1976-02-24_07',
    'full_text': 'In der Fraktion wurde ich aufgefordert, bevor Kreisky und Androsch kamen die berichten sollten, einen Kurzbericht zur Zeitüberbrückung zu geben. Ich referierte den Genossen über die Elektrizitätspreise und über die Ölpreisverhandlungen. Diskussion gab es keine. Benya hat mir dann nur abends bei 75 Jahre Konsumverband mitgeteilt, dass im Horwath von Burgenland angerufen hat, um eine eventuell noch weitere Elektrizitätspreiserhöhung abzuringen[?]. Benya hat ihm ganz kalt und hart auseinandergesetzt, dass auch nicht 1 % mehr gegeben wird. Er meinte mit Recht, dass hier von unserer Seite bis zur höchstmöglichen Lösung gegangen wurde.'}
```

**Comment by fsanzl** [comment]
```xml:id``` becomes a random-looking html ```id``` through ```<p id="{local:makeId(.)}" class="yes-index>``` when transformed by editions.xsl.  I need to find out the mechanism to open the search results on the right paragraph

**Comment by csae8092** [comment]
> `xml:id` becomes a random-looking html `id` through `<p id="{local:makeId(.)}" class="yes-index>` when transformed by editions.xsl instead of being kept as-is.

you can remove this xsl directive, or even better rewrite it so that it only applies on `tei:p` elements without `@xml:ids`

**Comment by fsanzl** [comment]
Sorry, I forgot the indication above. I already sorted the <p id> out yesterday

**Comment by fsanzl** [comment]
- [ ] Persons does something but not quite what was expected
- [ ] Months go in slider 0-11 instead 1-12. On top, they show the internal timestamp instead of presenting them in a human-readable guise  
- [ ] CSS to address white chars on white bg

**Comment by fsanzl** [comment]
It seems ok to me. The font color of the refinements would be better addressed in the CSS.
