### ISSUE TITLE
typesense refinement list checked

### ISSUE THREAD

**Issue by rausch-supola** [fun-with-editions/staribacher-static#40]
the checkbox next to the items in the refinement list does not change when one item is chosen. Should be colored or something

**Comment by fsanzl** [comment]
At least the latest deploy I can see a check mark when I select an item. Can you verify if it works now?

**Comment by rausch-supola** [comment]
Now it looks like this:

<img width="233" alt="image" src="https://github.com/fun-with-editions/staribacher-static/assets/143901391/e3ff95da-3f89-4b70-841c-5f74b8aa9072">
