### ISSUE TITLE
add para-texts from original application 

### ISSUE THREAD

**Issue by csae8092** [fun-with-editions/staribacher-static#54]
https://staribacher.acdh.oeaw.ac.at/projekt.html
https://staribacher.acdh.oeaw.ac.at/kontakt.html

**Comment by rausch-supola** [comment]
I inserted a lot of p elements, because insertion of br was ignored

**Comment by csae8092** [comment]
That's due to some legacy bug in the build.xml. here all br/ tags are modified with search and replace, please have a look into this file and remove the evil doing lines. Thanks
