### ISSUE TITLE
setup workflow to fetch data from staribacher data

### ISSUE THREAD

**Issue by cfhaak** [fun-with-editions/staribacher-static#7]
Please fetch data from the data repo as discussed.
Find the discussed example [here](https://github.com/bundesverfassung-oesterreich/bv-static)

**Comment by csae8092** [comment]
pst, cookiecutter provided an almost working fetch data script already
https://github.com/fun-with-editions/staribacher-static/blob/main/fetch_data.sh

maybe some search&replace is needed; something like `dse-static` -> `staribacher-data`

**Comment by cfhaak** [comment]
@rausch-supola did it already i think

**Comment by cfhaak** [comment]
@rausch-supola 
Everything seems to work fine! But as you already mentioned, there are some other interesting folders with index-files etc. in the [data repo. ](https://github.com/fun-with-editions/staribacher-data/tree/main/data) Please adjust the fetch script to get them too.
