### ISSUE TITLE
 readability

### ISSUE THREAD

**Issue by cfhaak** [fun-with-editions/staribacher-static#72]
Some of the pages like the searchpage or the toc can't be read well. Please provide a background, maybe like it was already done for the edition page. Text directly over the picture doesn't seem like a good solution.

**Comment by cfhaak** [comment]
Does this have to do with https://github.com/fun-with-editions/staribacher-static/issues/64 ?

**Comment by cfhaak** [comment]
Maybe something semi-transparent would be the best of both worlds?

**Comment by cfhaak** [comment]
@rausch-supola @kisram and me agreed, that having the contents over the images with some (semi-transparent?) backgrounds behind textual contents would be best.

**Comment by cfhaak** [comment]
Cool, way better. 
But now the image doesn't cover the full background (on my device). Instead there is a colored background visible on roughly 1/3 of the screen.
Also on pages like [this](https://fun-with-editions.github.io/staribacher-static/about.html) the text still runs under over the image.

**Comment by rausch-supola** [comment]
@cfhaak I think these issues should be solved by #86 and #88 by now. There were problems after including the footer

**Comment by cfhaak** [comment]
@rausch-supola cool, thx
